In [2]:
import datetime
import time
import calendar
import pytz
import pandas as pd
import numpy as np
import matplotlib

In [3]:
# df1 = pd.read_csv("quote_nasdaq_aapl_m1_2011.csv")
# dlen = len(df1)
# print dlen

In [4]:
#---------------------------------------------------
# Load a CSV file to a DataFrame
#---------------------------------------------------

print "Load CSV to DataFrame:"
df1 = pd.read_csv("quote_nasdaq_aapl_m1_2011_v2.csv")
print "df_len =",len(df1)

Load CSV to DataFrame:
df_len = 98100

In [4]:
#-------------------------------
# Test-1: Select single column
#-------------------------------
# Column = VOLUME

# by column name
sel = df1.ix[:,"VOLUME"]
print "Test-1.1:\n",sel,"\n"

# by coulumn index
sel = df1.ix[:,7]    # col-7=VOLUME
print "Test-1.2:\n",sel,"\n"

# by column name
sel = df1["VOLUME"]
print "Test-1.3:\n",sel,"\n"

# by dataframe property
sel = df1.VOLUME
print "Test-1.4:\n",sel,"\n"

Test-1.1:
0        153490
1        115484
2         85813
3         82506
4         72088
5         97056
6         62576
7        101856
8        139026
9        131626
10       150637
11       145934
12       161607
13       142252
14        85264
15       121747
16        83604
17        71052
18        73567
19        60314
20        97333
21        75191
22        90626
23        52826
24        55036
25        60638
26        54550
27        44626
28        73209
29        27308
          ...
98070     14059
98071      8086
98072     17341
98073     11333
98074     21225
98075     18305
98076     36448
98077     20203
98078     11003
98079     32730
98080     30931
98081     15096
98082     13893
98083     21238
98084     20532
98085     27253
98086     28603
98087     38756
98088     48780
98089     58206
98090     74251
98091     43524
98092     26911
98093     30260
98094     59983
98095     58225
98096     35405
98097     75023
98098     80455
98099    137867
Name: VOLUME, dtype: int64

Test-1.2:
0        153490
1        115484
2         85813
3         82506
4         72088
5         97056
6         62576
7        101856
8        139026
9        131626
10       150637
11       145934
12       161607
13       142252
14        85264
15       121747
16        83604
17        71052
18        73567
19        60314
20        97333
21        75191
22        90626
23        52826
24        55036
25        60638
26        54550
27        44626
28        73209
29        27308
          ...
98070     14059
98071      8086
98072     17341
98073     11333
98074     21225
98075     18305
98076     36448
98077     20203
98078     11003
98079     32730
98080     30931
98081     15096
98082     13893
98083     21238
98084     20532
98085     27253
98086     28603
98087     38756
98088     48780
98089     58206
98090     74251
98091     43524
98092     26911
98093     30260
98094     59983
98095     58225
98096     35405
98097     75023
98098     80455
98099    137867
Name: VOLUME, dtype: int64

Test-1.3:
0        153490
1        115484
2         85813
3         82506
4         72088
5         97056
6         62576
7        101856
8        139026
9        131626
10       150637
11       145934
12       161607
13       142252
14        85264
15       121747
16        83604
17        71052
18        73567
19        60314
20        97333
21        75191
22        90626
23        52826
24        55036
25        60638
26        54550
27        44626
28        73209
29        27308
          ...
98070     14059
98071      8086
98072     17341
98073     11333
98074     21225
98075     18305
98076     36448
98077     20203
98078     11003
98079     32730
98080     30931
98081     15096
98082     13893
98083     21238
98084     20532
98085     27253
98086     28603
98087     38756
98088     48780
98089     58206
98090     74251
98091     43524
98092     26911
98093     30260
98094     59983
98095     58225
98096     35405
98097     75023
98098     80455
98099    137867
Name: VOLUME, dtype: int64

Test-1.4:
0        153490
1        115484
2         85813
3         82506
4         72088
5         97056
6         62576
7        101856
8        139026
9        131626
10       150637
11       145934
12       161607
13       142252
14        85264
15       121747
16        83604
17        71052
18        73567
19        60314
20        97333
21        75191
22        90626
23        52826
24        55036
25        60638
26        54550
27        44626
28        73209
29        27308
          ...
98070     14059
98071      8086
98072     17341
98073     11333
98074     21225
98075     18305
98076     36448
98077     20203
98078     11003
98079     32730
98080     30931
98081     15096
98082     13893
98083     21238
98084     20532
98085     27253
98086     28603
98087     38756
98088     48780
98089     58206
98090     74251
98091     43524
98092     26911
98093     30260
98094     59983
98095     58225
98096     35405
98097     75023
98098     80455
98099    137867
Name: VOLUME, dtype: int64

In [5]:
#---------------------------------
# Test-2: Select multiple columns 
#---------------------------------
# Column = OPEN,CLOSE,VOLUME

# by column names
sel = df1.ix[:,["OPEN","CLOSE","VOLUME"]]
print "Test-2.1:\n",sel,"\n"

# by column indices
sel = df1.ix[:,[3,6,7]]     # Col-3=OPEN, Col-6=CLOSE, Col-7=VOLUME
print "Test-2.2:\n",sel,"\n"

#  by column indices
sel = df1[[3,6,7]]     # Col-3=OPEN, Col-6=CLOSE, Col-7=VOLUME
print "Test-2.3:\n",sel,"\n"

Test-2.1:
         OPEN   CLOSE  VOLUME
0      325.47  325.27  153490
1      325.23  325.59  115484
2      325.55  325.49   85813
3      325.44  325.35   82506
4      325.35  325.39   72088
5      325.41  325.55   97056
6      325.56  325.60   62576
7      325.57  326.00  101856
8      326.00  326.23  139026
9      326.25  326.55  131626
10     326.55  326.70  150637
11     326.71  327.03  145934
12     326.97  327.21  161607
13     327.23  326.95  142252
14     326.98  327.23   85264
15     327.24  327.45  121747
16     327.47  327.55   83604
17     327.54  327.72   71052
18     327.66  327.75   73567
19     327.79  327.81   60314
20     327.80  327.67   97333
21     327.67  327.49   75191
22     327.48  327.20   90626
23     327.20  327.27   52826
24     327.27  327.40   55036
25     327.37  327.66   60638
26     327.61  327.64   54550
27     327.67  327.69   44626
28     327.71  327.43   73209
29     327.44  327.47   27308
...       ...     ...     ...
98070  405.00  405.00   14059
98071  404.99  405.00    8086
98072  404.98  404.99   17341
98073  404.99  404.99   11333
98074  404.99  404.95   21225
98075  404.95  404.98   18305
98076  404.98  404.88   36448
98077  404.88  404.91   20203
98078  404.90  404.93   11003
98079  404.93  404.90   32730
98080  404.89  404.87   30931
98081  404.87  404.87   15096
98082  404.88  404.88   13893
98083  404.85  404.86   21238
98084  404.86  404.82   20532
98085  404.81  404.82   27253
98086  404.82  404.80   28603
98087  404.82  404.75   38756
98088  404.73  404.75   48780
98089  404.75  404.65   58206
98090  404.65  404.81   74251
98091  404.80  404.80   43524
98092  404.79  404.84   26911
98093  404.81  404.84   30260
98094  404.84  404.79   59983
98095  404.80  404.81   58225
98096  404.81  404.81   35405
98097  404.83  404.92   75023
98098  404.91  404.97   80455
98099  404.99  404.99  137867

[98100 rows x 3 columns]

Test-2.2:
         OPEN   CLOSE  VOLUME
0      325.47  325.27  153490
1      325.23  325.59  115484
2      325.55  325.49   85813
3      325.44  325.35   82506
4      325.35  325.39   72088
5      325.41  325.55   97056
6      325.56  325.60   62576
7      325.57  326.00  101856
8      326.00  326.23  139026
9      326.25  326.55  131626
10     326.55  326.70  150637
11     326.71  327.03  145934
12     326.97  327.21  161607
13     327.23  326.95  142252
14     326.98  327.23   85264
15     327.24  327.45  121747
16     327.47  327.55   83604
17     327.54  327.72   71052
18     327.66  327.75   73567
19     327.79  327.81   60314
20     327.80  327.67   97333
21     327.67  327.49   75191
22     327.48  327.20   90626
23     327.20  327.27   52826
24     327.27  327.40   55036
25     327.37  327.66   60638
26     327.61  327.64   54550
27     327.67  327.69   44626
28     327.71  327.43   73209
29     327.44  327.47   27308
...       ...     ...     ...
98070  405.00  405.00   14059
98071  404.99  405.00    8086
98072  404.98  404.99   17341
98073  404.99  404.99   11333
98074  404.99  404.95   21225
98075  404.95  404.98   18305
98076  404.98  404.88   36448
98077  404.88  404.91   20203
98078  404.90  404.93   11003
98079  404.93  404.90   32730
98080  404.89  404.87   30931
98081  404.87  404.87   15096
98082  404.88  404.88   13893
98083  404.85  404.86   21238
98084  404.86  404.82   20532
98085  404.81  404.82   27253
98086  404.82  404.80   28603
98087  404.82  404.75   38756
98088  404.73  404.75   48780
98089  404.75  404.65   58206
98090  404.65  404.81   74251
98091  404.80  404.80   43524
98092  404.79  404.84   26911
98093  404.81  404.84   30260
98094  404.84  404.79   59983
98095  404.80  404.81   58225
98096  404.81  404.81   35405
98097  404.83  404.92   75023
98098  404.91  404.97   80455
98099  404.99  404.99  137867

[98100 rows x 3 columns]

Test-2.3:
         OPEN   CLOSE  VOLUME
0      325.47  325.27  153490
1      325.23  325.59  115484
2      325.55  325.49   85813
3      325.44  325.35   82506
4      325.35  325.39   72088
5      325.41  325.55   97056
6      325.56  325.60   62576
7      325.57  326.00  101856
8      326.00  326.23  139026
9      326.25  326.55  131626
10     326.55  326.70  150637
11     326.71  327.03  145934
12     326.97  327.21  161607
13     327.23  326.95  142252
14     326.98  327.23   85264
15     327.24  327.45  121747
16     327.47  327.55   83604
17     327.54  327.72   71052
18     327.66  327.75   73567
19     327.79  327.81   60314
20     327.80  327.67   97333
21     327.67  327.49   75191
22     327.48  327.20   90626
23     327.20  327.27   52826
24     327.27  327.40   55036
25     327.37  327.66   60638
26     327.61  327.64   54550
27     327.67  327.69   44626
28     327.71  327.43   73209
29     327.44  327.47   27308
...       ...     ...     ...
98070  405.00  405.00   14059
98071  404.99  405.00    8086
98072  404.98  404.99   17341
98073  404.99  404.99   11333
98074  404.99  404.95   21225
98075  404.95  404.98   18305
98076  404.98  404.88   36448
98077  404.88  404.91   20203
98078  404.90  404.93   11003
98079  404.93  404.90   32730
98080  404.89  404.87   30931
98081  404.87  404.87   15096
98082  404.88  404.88   13893
98083  404.85  404.86   21238
98084  404.86  404.82   20532
98085  404.81  404.82   27253
98086  404.82  404.80   28603
98087  404.82  404.75   38756
98088  404.73  404.75   48780
98089  404.75  404.65   58206
98090  404.65  404.81   74251
98091  404.80  404.80   43524
98092  404.79  404.84   26911
98093  404.81  404.84   30260
98094  404.84  404.79   59983
98095  404.80  404.81   58225
98096  404.81  404.81   35405
98097  404.83  404.92   75023
98098  404.91  404.97   80455
98099  404.99  404.99  137867

[98100 rows x 3 columns]

In [6]:
#---------------------------------
# Test-3: Select range of rows
#---------------------------------

# Sample-1: by index of row ................

# Method-1:
sel = df1[0:10]  # row-0 to row-9
print "Test-3.1.1:\n",sel,"\n"

# Method-2:
sel = df1.ix[0:9,:] # row-0 to row-9
print "Test-3.1.2:\n",sel,"\n"


# Sample-2: by index of row with multiple columns ................

# Method-1: columns by name
sel = df1.ix[0:9,["OPEN","CLOSE","VOLUME"]]
print "Test-3.2.1:\n",sel,"\n"

# Method-2: columns by index
sel = df1.ix[0:9,[3,6,7]]
print "Test-3.2.2:\n",sel,"\n"

# Method-3: columns by range
sel = df1.ix[0:9,3:8]  # row0-9,col3-7
print "Test-3.2.3:\n",sel,"\n"

Test-3.1.1:
         DATE  TIME   TIMESTAMP    OPEN    HIGH     LOW   CLOSE  VOLUME
0  01/03/2011   930  1294047000  325.47  326.00  325.00  325.27  153490
1  01/03/2011   931  1294047060  325.23  325.70  324.84  325.59  115484
2  01/03/2011   932  1294047120  325.55  325.65  325.39  325.49   85813
3  01/03/2011   933  1294047180  325.44  325.59  325.19  325.35   82506
4  01/03/2011   934  1294047240  325.35  325.42  325.23  325.39   72088
5  01/03/2011   935  1294047300  325.41  325.60  325.38  325.55   97056
6  01/03/2011   936  1294047360  325.56  325.70  325.50  325.60   62576
7  01/03/2011   937  1294047420  325.57  326.00  325.55  326.00  101856
8  01/03/2011   938  1294047480  326.00  326.26  325.93  326.23  139026
9  01/03/2011   939  1294047540  326.25  326.74  326.19  326.55  131626

Test-3.1.2:
         DATE  TIME   TIMESTAMP    OPEN    HIGH     LOW   CLOSE  VOLUME
0  01/03/2011   930  1294047000  325.47  326.00  325.00  325.27  153490
1  01/03/2011   931  1294047060  325.23  325.70  324.84  325.59  115484
2  01/03/2011   932  1294047120  325.55  325.65  325.39  325.49   85813
3  01/03/2011   933  1294047180  325.44  325.59  325.19  325.35   82506
4  01/03/2011   934  1294047240  325.35  325.42  325.23  325.39   72088
5  01/03/2011   935  1294047300  325.41  325.60  325.38  325.55   97056
6  01/03/2011   936  1294047360  325.56  325.70  325.50  325.60   62576
7  01/03/2011   937  1294047420  325.57  326.00  325.55  326.00  101856
8  01/03/2011   938  1294047480  326.00  326.26  325.93  326.23  139026
9  01/03/2011   939  1294047540  326.25  326.74  326.19  326.55  131626

Test-3.2.1:
     OPEN   CLOSE  VOLUME
0  325.47  325.27  153490
1  325.23  325.59  115484
2  325.55  325.49   85813
3  325.44  325.35   82506
4  325.35  325.39   72088
5  325.41  325.55   97056
6  325.56  325.60   62576
7  325.57  326.00  101856
8  326.00  326.23  139026
9  326.25  326.55  131626

Test-3.2.2:
     OPEN   CLOSE  VOLUME
0  325.47  325.27  153490
1  325.23  325.59  115484
2  325.55  325.49   85813
3  325.44  325.35   82506
4  325.35  325.39   72088
5  325.41  325.55   97056
6  325.56  325.60   62576
7  325.57  326.00  101856
8  326.00  326.23  139026
9  326.25  326.55  131626

Test-3.2.3:
     OPEN    HIGH     LOW   CLOSE  VOLUME
0  325.47  326.00  325.00  325.27  153490
1  325.23  325.70  324.84  325.59  115484
2  325.55  325.65  325.39  325.49   85813
3  325.44  325.59  325.19  325.35   82506
4  325.35  325.42  325.23  325.39   72088
5  325.41  325.60  325.38  325.55   97056
6  325.56  325.70  325.50  325.60   62576
7  325.57  326.00  325.55  326.00  101856
8  326.00  326.26  325.93  326.23  139026
9  326.25  326.74  326.19  326.55  131626

In [7]:
#--------------------------------------
# Test-4: Select multiple rows by index
#--------------------------------------

sel = df1.ix[[0,2,4,6],:]
print "Test-4.1:\n",sel,"\n"

sel = df1.ix[[0,2,4,6],3:8]
print "Test-4.2:\n",sel,"\n"

sel = df1.ix[[0,2,4,6],[3,6,7]]
print "Test-4.3:\n",sel,"\n"

sel = df1.ix[[0,2,4,6],["OPEN","CLOSE","VOLUME"]]
print "Test-4.4:\n",sel,"\n"

Test-4.1:
         DATE  TIME   TIMESTAMP    OPEN    HIGH     LOW   CLOSE  VOLUME
0  01/03/2011   930  1294047000  325.47  326.00  325.00  325.27  153490
2  01/03/2011   932  1294047120  325.55  325.65  325.39  325.49   85813
4  01/03/2011   934  1294047240  325.35  325.42  325.23  325.39   72088
6  01/03/2011   936  1294047360  325.56  325.70  325.50  325.60   62576

Test-4.2:
     OPEN    HIGH     LOW   CLOSE  VOLUME
0  325.47  326.00  325.00  325.27  153490
2  325.55  325.65  325.39  325.49   85813
4  325.35  325.42  325.23  325.39   72088
6  325.56  325.70  325.50  325.60   62576

Test-4.3:
     OPEN   CLOSE  VOLUME
0  325.47  325.27  153490
2  325.55  325.49   85813
4  325.35  325.39   72088
6  325.56  325.60   62576

Test-4.4:
     OPEN   CLOSE  VOLUME
0  325.47  325.27  153490
2  325.55  325.49   85813
4  325.35  325.39   72088
6  325.56  325.60   62576

In [8]:
#---------------------------------
# Test-5: Select by conditions
#---------------------------------

# Select rows by conditions
sel = df1[(df1.TIME>=1000) & (df1.TIME<1005)]    # All of the records from 10:00 to 10:05
print "Test-5.1.1:\n",sel,"\n"

sel = df1.ix[(df1.TIME>=1000) & (df1.TIME<1005),:]    # All of the records from 10:00 to 10:05
print "Test-5.1.2:\n",sel,"\n"

sel = df1.ix[(df1.CLOSE>=400) & (df1.CLOSE<405),:]    # All of the records with CLOSE from 400.00 to 405.00
print "Test-5.1.3:\n",sel,"\n"


# Select rows by conditions and columns by series
sel = df1.ix[(df1.TIME>=1000) & (df1.TIME<1005),["OPEN","CLOSE","VOLUME"]]    # All of the records from 10:00 to 10:05 with OPEN/CLOSE/VOLUME
print "Test-5.2.1:\n",sel,"\n"

sel = df1.ix[(df1.TIME>=1000) & (df1.TIME<1005),[3,6,7]]    # All of the records from 10:00 to 10:05 with OPEN/CLOSE/VOLUME
print "Test-5.2.2\n",sel,"\n"

sel = df1.ix[(df1.CLOSE>=400) & (df1.CLOSE<405),["DATE","CLOSE","VOLUME"]]    # All of the records with CLOSE from 400.00 to 405.00
print "Test-5.2.3:\n",sel,"\n"

Test-5.1.1:
             DATE  TIME   TIMESTAMP    OPEN    HIGH     LOW   CLOSE  VOLUME
30     01/03/2011  1000  1294048800  327.47  327.58  327.39  327.42   53308
31     01/03/2011  1001  1294048860  327.44  327.53  327.37  327.45   33067
32     01/03/2011  1002  1294048920  327.44  327.60  327.37  327.52   63279
33     01/03/2011  1003  1294048980  327.53  327.70  327.50  327.61   45473
34     01/03/2011  1004  1294049040  327.61  327.85  327.57  327.80   95241
420    01/04/2011  1000  1294135200  331.19  331.43  331.14  331.42   41752
421    01/04/2011  1001  1294135260  331.43  331.50  331.35  331.46   39651
422    01/04/2011  1002  1294135320  331.42  331.49  331.10  331.15   45667
423    01/04/2011  1003  1294135380  331.16  331.45  331.09  331.21   34268
424    01/04/2011  1004  1294135440  331.26  331.49  331.19  331.37   41272
810    01/05/2011  1000  1294221600  331.18  331.34  331.00  331.12   44033
811    01/05/2011  1001  1294221660  331.12  331.24  330.86  331.12   44635
812    01/05/2011  1002  1294221720  331.12  331.42  331.00  331.34   28589
813    01/05/2011  1003  1294221780  331.30  331.52  331.30  331.49   48860
814    01/05/2011  1004  1294221840  331.50  331.85  331.42  331.84   58948
1200   01/06/2011  1000  1294308000  334.50  334.68  334.48  334.60   43573
1201   01/06/2011  1001  1294308060  334.61  334.95  334.60  334.85   43943
1202   01/06/2011  1002  1294308120  334.84  335.01  334.83  334.99   54531
1203   01/06/2011  1003  1294308180  334.98  334.98  334.70  334.94   38528
1204   01/06/2011  1004  1294308240  334.93  334.93  334.72  334.79   24249
1590   01/07/2011  1000  1294394400  333.24  333.60  333.16  333.39   31798
1591   01/07/2011  1001  1294394460  333.36  333.75  333.32  333.61   30410
1592   01/07/2011  1002  1294394520  333.55  333.70  333.50  333.66   22062
1593   01/07/2011  1003  1294394580  333.61  333.77  333.49  333.76   22997
1594   01/07/2011  1004  1294394640  333.71  333.97  333.65  333.82   34242
1980   01/10/2011  1000  1294653600  339.32  339.37  338.92  338.95  123261
1981   01/10/2011  1001  1294653660  338.92  338.97  338.34  338.47  119204
1982   01/10/2011  1002  1294653720  338.44  338.69  338.27  338.64   95233
1983   01/10/2011  1003  1294653780  338.68  339.15  338.62  339.09  104928
1984   01/10/2011  1004  1294653840  339.10  339.33  339.00  339.26   86450
...           ...   ...         ...     ...     ...     ...     ...     ...
95790  12/22/2011  1000  1324548000  398.25  398.42  398.16  398.31   18437
95791  12/22/2011  1001  1324548060  398.36  398.64  398.24  398.61   28703
95792  12/22/2011  1002  1324548120  398.58  398.60  398.25  398.37   26192
95793  12/22/2011  1003  1324548180  398.43  398.43  397.95  397.95   29749
95794  12/22/2011  1004  1324548240  397.95  398.11  397.81  398.00   41775
96180  12/23/2011  1000  1324634400  400.09  400.25  400.02  400.02   25301
96181  12/23/2011  1001  1324634460  400.04  400.34  400.01  400.31   32781
96182  12/23/2011  1002  1324634520  400.35  400.35  400.19  400.21   12411
96183  12/23/2011  1003  1324634580  400.21  400.40  400.17  400.26   34354
96184  12/23/2011  1004  1324634640  400.26  400.35  400.22  400.30   15800
96570  12/27/2011  1000  1324980000  408.14  408.68  407.90  408.62   62138
96571  12/27/2011  1001  1324980060  408.56  408.61  408.01  408.20   44023
96572  12/27/2011  1002  1324980120  408.20  408.26  407.82  407.94   55264
96573  12/27/2011  1003  1324980180  407.90  408.07  407.70  407.91   66764
96574  12/27/2011  1004  1324980240  407.91  408.04  407.78  407.97   28724
96960  12/28/2011  1000  1325066400  405.02  405.11  404.92  405.04   33848
96961  12/28/2011  1001  1325066460  405.04  405.07  404.81  404.95   34741
96962  12/28/2011  1002  1325066520  404.88  405.17  404.88  404.99   30295
96963  12/28/2011  1003  1325066580  404.98  405.11  404.80  404.85   20780
96964  12/28/2011  1004  1325066640  404.85  404.95  404.65  404.82   36989
97350  12/29/2011  1000  1325152800  402.21  402.31  402.08  402.22   31996
97351  12/29/2011  1001  1325152860  402.20  402.30  402.11  402.17   32564
97352  12/29/2011  1002  1325152920  402.12  402.16  401.89  401.91   44294
97353  12/29/2011  1003  1325152980  401.93  401.93  401.17  401.21   71021
97354  12/29/2011  1004  1325153040  401.21  401.36  400.72  400.97   78898
97740  12/30/2011  1000  1325239200  405.37  405.44  405.31  405.43   21896
97741  12/30/2011  1001  1325239260  405.44  405.75  405.40  405.70   44146
97742  12/30/2011  1002  1325239320  405.70  405.92  405.68  405.83   43688
97743  12/30/2011  1003  1325239380  405.88  406.22  405.85  406.16   70106
97744  12/30/2011  1004  1325239440  406.16  406.18  406.01  406.16   29788

[1260 rows x 8 columns]

Test-5.1.2:
             DATE  TIME   TIMESTAMP    OPEN    HIGH     LOW   CLOSE  VOLUME
30     01/03/2011  1000  1294048800  327.47  327.58  327.39  327.42   53308
31     01/03/2011  1001  1294048860  327.44  327.53  327.37  327.45   33067
32     01/03/2011  1002  1294048920  327.44  327.60  327.37  327.52   63279
33     01/03/2011  1003  1294048980  327.53  327.70  327.50  327.61   45473
34     01/03/2011  1004  1294049040  327.61  327.85  327.57  327.80   95241
420    01/04/2011  1000  1294135200  331.19  331.43  331.14  331.42   41752
421    01/04/2011  1001  1294135260  331.43  331.50  331.35  331.46   39651
422    01/04/2011  1002  1294135320  331.42  331.49  331.10  331.15   45667
423    01/04/2011  1003  1294135380  331.16  331.45  331.09  331.21   34268
424    01/04/2011  1004  1294135440  331.26  331.49  331.19  331.37   41272
810    01/05/2011  1000  1294221600  331.18  331.34  331.00  331.12   44033
811    01/05/2011  1001  1294221660  331.12  331.24  330.86  331.12   44635
812    01/05/2011  1002  1294221720  331.12  331.42  331.00  331.34   28589
813    01/05/2011  1003  1294221780  331.30  331.52  331.30  331.49   48860
814    01/05/2011  1004  1294221840  331.50  331.85  331.42  331.84   58948
1200   01/06/2011  1000  1294308000  334.50  334.68  334.48  334.60   43573
1201   01/06/2011  1001  1294308060  334.61  334.95  334.60  334.85   43943
1202   01/06/2011  1002  1294308120  334.84  335.01  334.83  334.99   54531
1203   01/06/2011  1003  1294308180  334.98  334.98  334.70  334.94   38528
1204   01/06/2011  1004  1294308240  334.93  334.93  334.72  334.79   24249
1590   01/07/2011  1000  1294394400  333.24  333.60  333.16  333.39   31798
1591   01/07/2011  1001  1294394460  333.36  333.75  333.32  333.61   30410
1592   01/07/2011  1002  1294394520  333.55  333.70  333.50  333.66   22062
1593   01/07/2011  1003  1294394580  333.61  333.77  333.49  333.76   22997
1594   01/07/2011  1004  1294394640  333.71  333.97  333.65  333.82   34242
1980   01/10/2011  1000  1294653600  339.32  339.37  338.92  338.95  123261
1981   01/10/2011  1001  1294653660  338.92  338.97  338.34  338.47  119204
1982   01/10/2011  1002  1294653720  338.44  338.69  338.27  338.64   95233
1983   01/10/2011  1003  1294653780  338.68  339.15  338.62  339.09  104928
1984   01/10/2011  1004  1294653840  339.10  339.33  339.00  339.26   86450
...           ...   ...         ...     ...     ...     ...     ...     ...
95790  12/22/2011  1000  1324548000  398.25  398.42  398.16  398.31   18437
95791  12/22/2011  1001  1324548060  398.36  398.64  398.24  398.61   28703
95792  12/22/2011  1002  1324548120  398.58  398.60  398.25  398.37   26192
95793  12/22/2011  1003  1324548180  398.43  398.43  397.95  397.95   29749
95794  12/22/2011  1004  1324548240  397.95  398.11  397.81  398.00   41775
96180  12/23/2011  1000  1324634400  400.09  400.25  400.02  400.02   25301
96181  12/23/2011  1001  1324634460  400.04  400.34  400.01  400.31   32781
96182  12/23/2011  1002  1324634520  400.35  400.35  400.19  400.21   12411
96183  12/23/2011  1003  1324634580  400.21  400.40  400.17  400.26   34354
96184  12/23/2011  1004  1324634640  400.26  400.35  400.22  400.30   15800
96570  12/27/2011  1000  1324980000  408.14  408.68  407.90  408.62   62138
96571  12/27/2011  1001  1324980060  408.56  408.61  408.01  408.20   44023
96572  12/27/2011  1002  1324980120  408.20  408.26  407.82  407.94   55264
96573  12/27/2011  1003  1324980180  407.90  408.07  407.70  407.91   66764
96574  12/27/2011  1004  1324980240  407.91  408.04  407.78  407.97   28724
96960  12/28/2011  1000  1325066400  405.02  405.11  404.92  405.04   33848
96961  12/28/2011  1001  1325066460  405.04  405.07  404.81  404.95   34741
96962  12/28/2011  1002  1325066520  404.88  405.17  404.88  404.99   30295
96963  12/28/2011  1003  1325066580  404.98  405.11  404.80  404.85   20780
96964  12/28/2011  1004  1325066640  404.85  404.95  404.65  404.82   36989
97350  12/29/2011  1000  1325152800  402.21  402.31  402.08  402.22   31996
97351  12/29/2011  1001  1325152860  402.20  402.30  402.11  402.17   32564
97352  12/29/2011  1002  1325152920  402.12  402.16  401.89  401.91   44294
97353  12/29/2011  1003  1325152980  401.93  401.93  401.17  401.21   71021
97354  12/29/2011  1004  1325153040  401.21  401.36  400.72  400.97   78898
97740  12/30/2011  1000  1325239200  405.37  405.44  405.31  405.43   21896
97741  12/30/2011  1001  1325239260  405.44  405.75  405.40  405.70   44146
97742  12/30/2011  1002  1325239320  405.70  405.92  405.68  405.83   43688
97743  12/30/2011  1003  1325239380  405.88  406.22  405.85  406.16   70106
97744  12/30/2011  1004  1325239440  406.16  406.18  406.01  406.16   29788

[1260 rows x 8 columns]

Test-5.1.3:
             DATE  TIME   TIMESTAMP    OPEN    HIGH     LOW   CLOSE  VOLUME
54990  07/26/2011   930  1311672600  400.00  400.88  399.68  400.73  468455
54991  07/26/2011   931  1311672660  400.76  401.42  400.51  401.41  188156
54992  07/26/2011   932  1311672720  401.42  401.71  401.35  401.56  173927
54993  07/26/2011   933  1311672780  401.56  401.69  401.06  401.21  159260
54994  07/26/2011   934  1311672840  401.21  401.21  400.40  400.63  183092
54995  07/26/2011   935  1311672900  400.63  400.69  400.25  400.49  121491
54996  07/26/2011   936  1311672960  400.48  401.69  400.44  401.44  166774
54997  07/26/2011   937  1311673020  401.39  401.85  401.34  401.76  128228
54998  07/26/2011   938  1311673080  401.70  402.50  401.69  402.47  169030
54999  07/26/2011   939  1311673140  402.48  402.86  402.20  402.51  203934
55000  07/26/2011   940  1311673200  402.51  403.09  402.25  403.03  175445
55001  07/26/2011   941  1311673260  403.07  403.24  402.86  403.06  162625
55002  07/26/2011   942  1311673320  403.11  403.45  403.04  403.35  103756
55003  07/26/2011   943  1311673380  403.35  403.40  402.27  402.36  187167
55004  07/26/2011   944  1311673440  402.36  402.75  402.16  402.24  111649
55005  07/26/2011   945  1311673500  402.22  402.30  401.33  401.45  175528
55006  07/26/2011   946  1311673560  401.42  402.11  401.41  401.87  107564
55007  07/26/2011   947  1311673620  401.87  402.49  401.87  402.27   74541
55008  07/26/2011   948  1311673680  402.15  402.47  402.00  402.28   90522
55009  07/26/2011   949  1311673740  402.25  402.65  402.01  402.65   60190
55010  07/26/2011   950  1311673800  402.61  402.69  401.90  401.95   87876
55011  07/26/2011   951  1311673860  401.90  401.91  401.50  401.72   87671
55012  07/26/2011   952  1311673920  401.71  402.10  401.70  401.87   58796
55013  07/26/2011   953  1311673980  401.85  402.17  401.80  402.11   61616
55014  07/26/2011   954  1311674040  402.07  402.21  401.59  401.66   79695
55015  07/26/2011   955  1311674100  401.67  401.68  400.78  400.78  118762
55016  07/26/2011   956  1311674160  400.78  401.15  400.50  401.10  135302
55017  07/26/2011   957  1311674220  401.11  401.47  400.80  400.91   96393
55018  07/26/2011   958  1311674280  400.91  401.00  400.75  400.83   74683
55019  07/26/2011   959  1311674340  400.83  401.03  400.69  400.99   87958
...           ...   ...         ...     ...     ...     ...     ...     ...
98059  12/30/2011  1519  1325258340  405.01  405.02  404.96  404.97   18263
98062  12/30/2011  1522  1325258520  405.02  405.03  404.97  404.98    6791
98072  12/30/2011  1532  1325259120  404.98  405.00  404.95  404.99   17341
98073  12/30/2011  1533  1325259180  404.99  405.03  404.97  404.99   11333
98074  12/30/2011  1534  1325259240  404.99  405.00  404.95  404.95   21225
98075  12/30/2011  1535  1325259300  404.95  405.26  404.95  404.98   18305
98076  12/30/2011  1536  1325259360  404.98  404.99  404.88  404.88   36448
98077  12/30/2011  1537  1325259420  404.88  404.94  404.85  404.91   20203
98078  12/30/2011  1538  1325259480  404.90  404.98  404.90  404.93   11003
98079  12/30/2011  1539  1325259540  404.93  404.94  404.89  404.90   32730
98080  12/30/2011  1540  1325259600  404.89  404.91  404.85  404.87   30931
98081  12/30/2011  1541  1325259660  404.87  404.89  404.85  404.87   15096
98082  12/30/2011  1542  1325259720  404.88  404.90  404.85  404.88   13893
98083  12/30/2011  1543  1325259780  404.85  404.89  404.84  404.86   21238
98084  12/30/2011  1544  1325259840  404.86  404.88  404.81  404.82   20532
98085  12/30/2011  1545  1325259900  404.81  404.88  404.80  404.82   27253
98086  12/30/2011  1546  1325259960  404.82  404.85  404.78  404.80   28603
98087  12/30/2011  1547  1325260020  404.82  404.83  404.73  404.75   38756
98088  12/30/2011  1548  1325260080  404.73  404.83  404.69  404.75   48780
98089  12/30/2011  1549  1325260140  404.75  404.76  404.64  404.65   58206
98090  12/30/2011  1550  1325260200  404.65  404.84  404.64  404.81   74251
98091  12/30/2011  1551  1325260260  404.80  404.84  404.75  404.80   43524
98092  12/30/2011  1552  1325260320  404.79  404.84  404.75  404.84   26911
98093  12/30/2011  1553  1325260380  404.81  404.85  404.78  404.84   30260
98094  12/30/2011  1554  1325260440  404.84  404.87  404.78  404.79   59983
98095  12/30/2011  1555  1325260500  404.80  404.84  404.76  404.81   58225
98096  12/30/2011  1556  1325260560  404.81  404.83  404.76  404.81   35405
98097  12/30/2011  1557  1325260620  404.83  404.92  404.80  404.92   75023
98098  12/30/2011  1558  1325260680  404.91  405.00  404.91  404.97   80455
98099  12/30/2011  1559  1325260740  404.99  405.01  404.87  404.99  137867

[4719 rows x 8 columns]

Test-5.2.1:
         OPEN   CLOSE  VOLUME
30     327.47  327.42   53308
31     327.44  327.45   33067
32     327.44  327.52   63279
33     327.53  327.61   45473
34     327.61  327.80   95241
420    331.19  331.42   41752
421    331.43  331.46   39651
422    331.42  331.15   45667
423    331.16  331.21   34268
424    331.26  331.37   41272
810    331.18  331.12   44033
811    331.12  331.12   44635
812    331.12  331.34   28589
813    331.30  331.49   48860
814    331.50  331.84   58948
1200   334.50  334.60   43573
1201   334.61  334.85   43943
1202   334.84  334.99   54531
1203   334.98  334.94   38528
1204   334.93  334.79   24249
1590   333.24  333.39   31798
1591   333.36  333.61   30410
1592   333.55  333.66   22062
1593   333.61  333.76   22997
1594   333.71  333.82   34242
1980   339.32  338.95  123261
1981   338.92  338.47  119204
1982   338.44  338.64   95233
1983   338.68  339.09  104928
1984   339.10  339.26   86450
...       ...     ...     ...
95790  398.25  398.31   18437
95791  398.36  398.61   28703
95792  398.58  398.37   26192
95793  398.43  397.95   29749
95794  397.95  398.00   41775
96180  400.09  400.02   25301
96181  400.04  400.31   32781
96182  400.35  400.21   12411
96183  400.21  400.26   34354
96184  400.26  400.30   15800
96570  408.14  408.62   62138
96571  408.56  408.20   44023
96572  408.20  407.94   55264
96573  407.90  407.91   66764
96574  407.91  407.97   28724
96960  405.02  405.04   33848
96961  405.04  404.95   34741
96962  404.88  404.99   30295
96963  404.98  404.85   20780
96964  404.85  404.82   36989
97350  402.21  402.22   31996
97351  402.20  402.17   32564
97352  402.12  401.91   44294
97353  401.93  401.21   71021
97354  401.21  400.97   78898
97740  405.37  405.43   21896
97741  405.44  405.70   44146
97742  405.70  405.83   43688
97743  405.88  406.16   70106
97744  406.16  406.16   29788

[1260 rows x 3 columns]

Test-5.2.2
         OPEN   CLOSE  VOLUME
30     327.47  327.42   53308
31     327.44  327.45   33067
32     327.44  327.52   63279
33     327.53  327.61   45473
34     327.61  327.80   95241
420    331.19  331.42   41752
421    331.43  331.46   39651
422    331.42  331.15   45667
423    331.16  331.21   34268
424    331.26  331.37   41272
810    331.18  331.12   44033
811    331.12  331.12   44635
812    331.12  331.34   28589
813    331.30  331.49   48860
814    331.50  331.84   58948
1200   334.50  334.60   43573
1201   334.61  334.85   43943
1202   334.84  334.99   54531
1203   334.98  334.94   38528
1204   334.93  334.79   24249
1590   333.24  333.39   31798
1591   333.36  333.61   30410
1592   333.55  333.66   22062
1593   333.61  333.76   22997
1594   333.71  333.82   34242
1980   339.32  338.95  123261
1981   338.92  338.47  119204
1982   338.44  338.64   95233
1983   338.68  339.09  104928
1984   339.10  339.26   86450
...       ...     ...     ...
95790  398.25  398.31   18437
95791  398.36  398.61   28703
95792  398.58  398.37   26192
95793  398.43  397.95   29749
95794  397.95  398.00   41775
96180  400.09  400.02   25301
96181  400.04  400.31   32781
96182  400.35  400.21   12411
96183  400.21  400.26   34354
96184  400.26  400.30   15800
96570  408.14  408.62   62138
96571  408.56  408.20   44023
96572  408.20  407.94   55264
96573  407.90  407.91   66764
96574  407.91  407.97   28724
96960  405.02  405.04   33848
96961  405.04  404.95   34741
96962  404.88  404.99   30295
96963  404.98  404.85   20780
96964  404.85  404.82   36989
97350  402.21  402.22   31996
97351  402.20  402.17   32564
97352  402.12  401.91   44294
97353  401.93  401.21   71021
97354  401.21  400.97   78898
97740  405.37  405.43   21896
97741  405.44  405.70   44146
97742  405.70  405.83   43688
97743  405.88  406.16   70106
97744  406.16  406.16   29788

[1260 rows x 3 columns]

Test-5.2.3:
             DATE   CLOSE  VOLUME
54990  07/26/2011  400.73  468455
54991  07/26/2011  401.41  188156
54992  07/26/2011  401.56  173927
54993  07/26/2011  401.21  159260
54994  07/26/2011  400.63  183092
54995  07/26/2011  400.49  121491
54996  07/26/2011  401.44  166774
54997  07/26/2011  401.76  128228
54998  07/26/2011  402.47  169030
54999  07/26/2011  402.51  203934
55000  07/26/2011  403.03  175445
55001  07/26/2011  403.06  162625
55002  07/26/2011  403.35  103756
55003  07/26/2011  402.36  187167
55004  07/26/2011  402.24  111649
55005  07/26/2011  401.45  175528
55006  07/26/2011  401.87  107564
55007  07/26/2011  402.27   74541
55008  07/26/2011  402.28   90522
55009  07/26/2011  402.65   60190
55010  07/26/2011  401.95   87876
55011  07/26/2011  401.72   87671
55012  07/26/2011  401.87   58796
55013  07/26/2011  402.11   61616
55014  07/26/2011  401.66   79695
55015  07/26/2011  400.78  118762
55016  07/26/2011  401.10  135302
55017  07/26/2011  400.91   96393
55018  07/26/2011  400.83   74683
55019  07/26/2011  400.99   87958
...           ...     ...     ...
98059  12/30/2011  404.97   18263
98062  12/30/2011  404.98    6791
98072  12/30/2011  404.99   17341
98073  12/30/2011  404.99   11333
98074  12/30/2011  404.95   21225
98075  12/30/2011  404.98   18305
98076  12/30/2011  404.88   36448
98077  12/30/2011  404.91   20203
98078  12/30/2011  404.93   11003
98079  12/30/2011  404.90   32730
98080  12/30/2011  404.87   30931
98081  12/30/2011  404.87   15096
98082  12/30/2011  404.88   13893
98083  12/30/2011  404.86   21238
98084  12/30/2011  404.82   20532
98085  12/30/2011  404.82   27253
98086  12/30/2011  404.80   28603
98087  12/30/2011  404.75   38756
98088  12/30/2011  404.75   48780
98089  12/30/2011  404.65   58206
98090  12/30/2011  404.81   74251
98091  12/30/2011  404.80   43524
98092  12/30/2011  404.84   26911
98093  12/30/2011  404.84   30260
98094  12/30/2011  404.79   59983

In [17]:
sel = df1.ix[(df1.index>=814) & (df1.TIME>=1000) & (df1.TIME<1005)]    # All of the records from 10:00 to 10:05
print "Test-5.1.1:\n",sel,"\n"
print sel.index
print sel.index[0], sel.index[len(sel)-1]

Test-5.1.1:
             DATE  TIME   TIMESTAMP    OPEN    HIGH     LOW   CLOSE  VOLUME
814    01/05/2011  1004  1294221840  331.50  331.85  331.42  331.84   58948
1200   01/06/2011  1000  1294308000  334.50  334.68  334.48  334.60   43573
1201   01/06/2011  1001  1294308060  334.61  334.95  334.60  334.85   43943
1202   01/06/2011  1002  1294308120  334.84  335.01  334.83  334.99   54531
1203   01/06/2011  1003  1294308180  334.98  334.98  334.70  334.94   38528
1204   01/06/2011  1004  1294308240  334.93  334.93  334.72  334.79   24249
1590   01/07/2011  1000  1294394400  333.24  333.60  333.16  333.39   31798
1591   01/07/2011  1001  1294394460  333.36  333.75  333.32  333.61   30410
1592   01/07/2011  1002  1294394520  333.55  333.70  333.50  333.66   22062
1593   01/07/2011  1003  1294394580  333.61  333.77  333.49  333.76   22997
1594   01/07/2011  1004  1294394640  333.71  333.97  333.65  333.82   34242
1980   01/10/2011  1000  1294653600  339.32  339.37  338.92  338.95  123261
1981   01/10/2011  1001  1294653660  338.92  338.97  338.34  338.47  119204
1982   01/10/2011  1002  1294653720  338.44  338.69  338.27  338.64   95233
1983   01/10/2011  1003  1294653780  338.68  339.15  338.62  339.09  104928
1984   01/10/2011  1004  1294653840  339.10  339.33  339.00  339.26   86450
2370   01/11/2011  1000  1294740000  341.94  341.94  341.35  341.67   98321
2371   01/11/2011  1001  1294740060  341.67  341.85  341.64  341.79   78597
2372   01/11/2011  1002  1294740120  341.84  342.14  341.78  342.12   75257
2373   01/11/2011  1003  1294740180  342.07  342.60  342.07  342.41   75839
2374   01/11/2011  1004  1294740240  342.41  342.72  342.32  342.45   58858
2760   01/12/2011  1000  1294826400  343.33  343.35  343.04  343.24   27959
2761   01/12/2011  1001  1294826460  343.24  343.32  343.10  343.30   33823
2762   01/12/2011  1002  1294826520  343.29  343.31  343.15  343.28   29638
2763   01/12/2011  1003  1294826580  343.26  343.28  343.05  343.06   33430
2764   01/12/2011  1004  1294826640  343.04  343.14  342.80  342.90   46438
3150   01/13/2011  1000  1294912800  344.30  344.33  344.02  344.30   45651
3151   01/13/2011  1001  1294912860  344.32  344.46  344.25  344.28   38575
3152   01/13/2011  1002  1294912920  344.24  344.27  344.03  344.03   30521
3153   01/13/2011  1003  1294912980  344.03  344.10  343.91  344.09   34846
...           ...   ...         ...     ...     ...     ...     ...     ...
95790  12/22/2011  1000  1324548000  398.25  398.42  398.16  398.31   18437
95791  12/22/2011  1001  1324548060  398.36  398.64  398.24  398.61   28703
95792  12/22/2011  1002  1324548120  398.58  398.60  398.25  398.37   26192
95793  12/22/2011  1003  1324548180  398.43  398.43  397.95  397.95   29749
95794  12/22/2011  1004  1324548240  397.95  398.11  397.81  398.00   41775
96180  12/23/2011  1000  1324634400  400.09  400.25  400.02  400.02   25301
96181  12/23/2011  1001  1324634460  400.04  400.34  400.01  400.31   32781
96182  12/23/2011  1002  1324634520  400.35  400.35  400.19  400.21   12411
96183  12/23/2011  1003  1324634580  400.21  400.40  400.17  400.26   34354
96184  12/23/2011  1004  1324634640  400.26  400.35  400.22  400.30   15800
96570  12/27/2011  1000  1324980000  408.14  408.68  407.90  408.62   62138
96571  12/27/2011  1001  1324980060  408.56  408.61  408.01  408.20   44023
96572  12/27/2011  1002  1324980120  408.20  408.26  407.82  407.94   55264
96573  12/27/2011  1003  1324980180  407.90  408.07  407.70  407.91   66764
96574  12/27/2011  1004  1324980240  407.91  408.04  407.78  407.97   28724
96960  12/28/2011  1000  1325066400  405.02  405.11  404.92  405.04   33848
96961  12/28/2011  1001  1325066460  405.04  405.07  404.81  404.95   34741
96962  12/28/2011  1002  1325066520  404.88  405.17  404.88  404.99   30295
96963  12/28/2011  1003  1325066580  404.98  405.11  404.80  404.85   20780
96964  12/28/2011  1004  1325066640  404.85  404.95  404.65  404.82   36989
97350  12/29/2011  1000  1325152800  402.21  402.31  402.08  402.22   31996
97351  12/29/2011  1001  1325152860  402.20  402.30  402.11  402.17   32564
97352  12/29/2011  1002  1325152920  402.12  402.16  401.89  401.91   44294
97353  12/29/2011  1003  1325152980  401.93  401.93  401.17  401.21   71021
97354  12/29/2011  1004  1325153040  401.21  401.36  400.72  400.97   78898
97740  12/30/2011  1000  1325239200  405.37  405.44  405.31  405.43   21896
97741  12/30/2011  1001  1325239260  405.44  405.75  405.40  405.70   44146
97742  12/30/2011  1002  1325239320  405.70  405.92  405.68  405.83   43688
97743  12/30/2011  1003  1325239380  405.88  406.22  405.85  406.16   70106
97744  12/30/2011  1004  1325239440  406.16  406.18  406.01  406.16   29788

[1246 rows x 8 columns]

Int64Index([  814,  1200,  1201,  1202,  1203,  1204,  1590,  1591,  1592,
             1593,
            ...
            97350, 97351, 97352, 97353, 97354, 97740, 97741, 97742, 97743,
            97744],
           dtype='int64', length=1246)
814 97744

In [ ]:
df2=df1[0:10]   # Actually no copying happened! df2 is only referenced to part of df1 by given range

In [18]:
df1.ix[1,"VOLUME"] += 10   # one cell of df1 is modified
print df1.ix[1,"VOLUME"]  # check the change
print df2                 # the corresponding cell in df2 should be changed as well

112253
         DATE  TIME   TIMESTAMP    OPEN    HIGH     LOW   CLOSE  VOLUME
0  01/03/2011   930  1294047000  325.47  326.00  325.00  325.27     789
1  01/03/2011   931  1294047060  325.23  325.70  324.84  325.59  112253
2  01/03/2011   932  1294047120  325.55  325.65  325.39  325.49   85813
3  01/03/2011   933  1294047180  325.44  325.59  325.19  325.35   82506
4  01/03/2011   934  1294047240  325.35  325.42  325.23  325.39   72088
5  01/03/2011   935  1294047300  325.41  325.60  325.38  325.55   97056
6  01/03/2011   936  1294047360  325.56  325.70  325.50  325.60   62576
7  01/03/2011   937  1294047420  325.57  326.00  325.55  326.00  101856
8  01/03/2011   938  1294047480  326.00  326.26  325.93  326.23  139026
9  01/03/2011   939  1294047540  326.25  326.74  326.19  326.55  131626