In [1]:
import time as tm

# numpy
import numpy as np
# pandas
import pandas as pd

In [2]:
# Make pseudo data set
code_low = 1000
code_high = 4000
dataset_size = 100000

codes = ['%s'%(x) for x in range(code_low, code_high)]   # list of codes
# dfCode = pd.DataFrame(data=codes, columns=["Code"])

data_codes = np.random.randint(low=code_low+100, 
                               high=code_high, 
                               size=dataset_size)  # 100items less than 'codes'
data_tagcodes = np.random.randint(low=1, 
                                  high=dataset_size*100, 
                                  size=dataset_size)
data_tags = ['Tag string is <Code=%4.4d, Tag=%8.8d>'%(x[0], x[1]) for x in zip(data_codes,data_tagcodes)] # create tag strings

dfData = pd.DataFrame(data=zip(data_codes, data_tags),
                      columns=["Code", "Tag"])          # The pseudo data set
dfData

       Code                                      Tag
0      2586  Tag string is <Code=2586, Tag=03745612>
1      1265  Tag string is <Code=1265, Tag=09020812>
2      2062  Tag string is <Code=2062, Tag=01208918>
3      1186  Tag string is <Code=1186, Tag=08848170>
4      1174  Tag string is <Code=1174, Tag=06998417>
5      3355  Tag string is <Code=3355, Tag=00165889>
6      3883  Tag string is <Code=3883, Tag=01318660>
7      1370  Tag string is <Code=1370, Tag=09864241>
8      3598  Tag string is <Code=3598, Tag=03410942>
9      2973  Tag string is <Code=2973, Tag=08775866>
10     2984  Tag string is <Code=2984, Tag=00656536>
11     3128  Tag string is <Code=3128, Tag=03806657>
12     2204  Tag string is <Code=2204, Tag=03108582>
13     1674  Tag string is <Code=1674, Tag=01357638>
14     2734  Tag string is <Code=2734, Tag=04230530>
15     3535  Tag string is <Code=3535, Tag=01416183>
16     3881  Tag string is <Code=3881, Tag=04397332>
17     1907  Tag string is <Code=1907, Tag=03586688>
18     3217  Tag string is <Code=3217, Tag=06920712>
19     2303  Tag string is <Code=2303, Tag=05658183>
20     3332  Tag string is <Code=3332, Tag=06711769>
21     2926  Tag string is <Code=2926, Tag=06546597>
22     1828  Tag string is <Code=1828, Tag=01196001>
23     3673  Tag string is <Code=3673, Tag=04496793>
24     1124  Tag string is <Code=1124, Tag=03843186>
25     3125  Tag string is <Code=3125, Tag=01917147>
26     3214  Tag string is <Code=3214, Tag=02117141>
27     1800  Tag string is <Code=1800, Tag=05217143>
28     1827  Tag string is <Code=1827, Tag=09413646>
29     3741  Tag string is <Code=3741, Tag=04677385>
...     ...                                      ...
99970  3152  Tag string is <Code=3152, Tag=05305886>
99971  3606  Tag string is <Code=3606, Tag=03367655>
99972  3576  Tag string is <Code=3576, Tag=07408921>
99973  3152  Tag string is <Code=3152, Tag=07372663>
99974  2868  Tag string is <Code=2868, Tag=02728233>
99975  1547  Tag string is <Code=1547, Tag=04789072>
99976  1240  Tag string is <Code=1240, Tag=01312424>
99977  3293  Tag string is <Code=3293, Tag=04735803>
99978  1645  Tag string is <Code=1645, Tag=04371668>
99979  2643  Tag string is <Code=2643, Tag=06778952>
99980  2953  Tag string is <Code=2953, Tag=03201006>
99981  1963  Tag string is <Code=1963, Tag=01563602>
99982  2858  Tag string is <Code=2858, Tag=08153546>
99983  2147  Tag string is <Code=2147, Tag=09293994>
99984  2186  Tag string is <Code=2186, Tag=03227605>
99985  2777  Tag string is <Code=2777, Tag=09252193>
99986  3666  Tag string is <Code=3666, Tag=08281439>
99987  3302  Tag string is <Code=3302, Tag=07275637>
99988  1169  Tag string is <Code=1169, Tag=07670637>
99989  1518  Tag string is <Code=1518, Tag=08239789>
99990  3076  Tag string is <Code=3076, Tag=09105501>
99991  1471  Tag string is <Code=1471, Tag=01331346>
99992  1895  Tag string is <Code=1895, Tag=00039133>
99993  1233  Tag string is <Code=1233, Tag=09906315>
99994  1403  Tag string is <Code=1403, Tag=06997349>
99995  2052  Tag string is <Code=2052, Tag=05763456>
99996  1146  Tag string is <Code=1146, Tag=05669758>
99997  3470  Tag string is <Code=3470, Tag=08786602>
99998  1807  Tag string is <Code=1807, Tag=07714699>
99999  1931  Tag string is <Code=1931, Tag=05197043>

[100000 rows x 2 columns]

In [3]:
tk1 = tm.clock()  # for benchmark

result = []  # list to store the sub-dataframe for each code
for code in codes:
    chk = dfData['Code'].isin([code])
    dfSub = dfData[chk]
    if len(dfSub) > 0:
        result.append(dfSub)
    
tk2 = tm.clock()

print 'count of result =', len(result)   # number of sub-dataframe
print 'time consumed =','%3.3f(s)'%(tk2-tk1)  # benchmark

count of result = 2900
time consumed = 3.782(s)

In [4]:
# Check result:
dfX = result[100]
print "result[100]: rows=%d\n"%(len(dfX)),dfX.head()
print

dfX = result[1000]
print "result[1000]: rows=%d\n"%(len(dfX)),dfX.head()

result[100]: rows=39
       Code                                      Tag
853    1200  Tag string is <Code=1200, Tag=03416731>
5875   1200  Tag string is <Code=1200, Tag=06932670>
6540   1200  Tag string is <Code=1200, Tag=06949203>
10964  1200  Tag string is <Code=1200, Tag=07234471>
12026  1200  Tag string is <Code=1200, Tag=03665587>

result[1000]: rows=34
       Code                                      Tag
4306   2100  Tag string is <Code=2100, Tag=02814187>
6741   2100  Tag string is <Code=2100, Tag=08001774>
8459   2100  Tag string is <Code=2100, Tag=08672318>
12842  2100  Tag string is <Code=2100, Tag=07650308>
18180  2100  Tag string is <Code=2100, Tag=00682527>

In [5]:
result[100]

       Code                                      Tag
853    1200  Tag string is <Code=1200, Tag=03416731>
5875   1200  Tag string is <Code=1200, Tag=06932670>
6540   1200  Tag string is <Code=1200, Tag=06949203>
10964  1200  Tag string is <Code=1200, Tag=07234471>
12026  1200  Tag string is <Code=1200, Tag=03665587>
14139  1200  Tag string is <Code=1200, Tag=05995853>
16353  1200  Tag string is <Code=1200, Tag=07173824>
17836  1200  Tag string is <Code=1200, Tag=03561659>
19450  1200  Tag string is <Code=1200, Tag=01655797>
24178  1200  Tag string is <Code=1200, Tag=02422183>
27168  1200  Tag string is <Code=1200, Tag=01458920>
28688  1200  Tag string is <Code=1200, Tag=05730608>
30197  1200  Tag string is <Code=1200, Tag=05111806>
31961  1200  Tag string is <Code=1200, Tag=02377821>
34477  1200  Tag string is <Code=1200, Tag=05667981>
38374  1200  Tag string is <Code=1200, Tag=05822415>
38967  1200  Tag string is <Code=1200, Tag=06526185>
40481  1200  Tag string is <Code=1200, Tag=06050978>
43405  1200  Tag string is <Code=1200, Tag=07847786>
46067  1200  Tag string is <Code=1200, Tag=04554213>
46724  1200  Tag string is <Code=1200, Tag=05297690>
59592  1200  Tag string is <Code=1200, Tag=09550267>
61257  1200  Tag string is <Code=1200, Tag=01821749>
64084  1200  Tag string is <Code=1200, Tag=00170942>
68422  1200  Tag string is <Code=1200, Tag=08110474>
69544  1200  Tag string is <Code=1200, Tag=08918356>
76001  1200  Tag string is <Code=1200, Tag=07482237>
76415  1200  Tag string is <Code=1200, Tag=05547457>
78880  1200  Tag string is <Code=1200, Tag=05348025>
78972  1200  Tag string is <Code=1200, Tag=01429244>
80293  1200  Tag string is <Code=1200, Tag=00115477>
80563  1200  Tag string is <Code=1200, Tag=05337269>
85217  1200  Tag string is <Code=1200, Tag=01456977>
90343  1200  Tag string is <Code=1200, Tag=00827213>
93801  1200  Tag string is <Code=1200, Tag=04798909>
96136  1200  Tag string is <Code=1200, Tag=03474484>
99327  1200  Tag string is <Code=1200, Tag=01698076>
99708  1200  Tag string is <Code=1200, Tag=08641202>
99881  1200  Tag string is <Code=1200, Tag=05791696>